# Copyright (c) 2026 Emmo "mo2000" Emminghaus mo2000 at mo2000 dot de
# SPDX-License-Identifier: AGPL-3.0-or-later
services:
  roundcube:
    image: roundcube/roundcubemail:latest
    hostname: roundcube
    environment:
      - TZ=${TZ}
      - ROUNDCUBEMAIL_DB_PASSWORD=${ROUNDCUBEMAIL_DB_PASSWORD}
      #- ROUNDCUBEMAIL_REQUEST_PATH=/roundcube
      - ROUNDCUBEMAIL_INSTALL_PLUGINS=1
      - ROUNDCUBEMAIL_COMPOSER_PLUGINS=johndoh/contextmenu
        # kolab/calendar
        # kolab/tasklist
        # sblaisot/html5_notifier

      - ROUNDCUBEMAIL_PLUGINS=
          managesieve,
          zipdownload,
          archive,
          filesystem_attachments,
          subscriptions_option,
          vcard_attachments,
          emoticons,
          virtuser_query,
          contextmenu,
          carddav,
          mailcow
      # eniugma,
      # calendar,
      # tasklist,
      # html5_notifier,
      # TODO!
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
- 
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME:-mailcow}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - IPV6_NETWORK=${IPV6_NETWORK:-fd00:dead:beef:cafe::}
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    volumes:
      - ./mailcow-roundcube/data/conf/roundcube:/var/roundcube/config:ro,Z
      - ./mailcow-roundcube/data/assets/roundcube/plugins:/var/www/html/plugins:Z
      #- ./mailcow-roundcube/data/assets/roundcube/plugins/mailcow:/var/www/html/plugins/mailcow:ro,Z
      - ./mailcow-roundcube/data/assets/roundcube/entrypoint-tasks:/entrypoint-tasks
      - mysql-socket-vol-1:/var/run/mysqld/:z
    labels:
      - "com.docker.compose.service=roundcube"
    restart: always
    networks:
      mailcow-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.100
        aliases:
          - roundcube

  nginx-mailcow:
    depends_on:
      - roundcube
    volumes:
      - ./mailcow-roundcube/data/conf/nginx/site.roundcube.conf:/etc/nginx/conf.d/site.roundcube.conf:ro,Z
      - ./mailcow-roundcube/data/conf/nginx/site.roundcube.custom:/etc/nginx/conf.d/site.roundcube.custom:ro,Z
      - ./mailcow-roundcube/data/conf/nginx/site.sogomiddleware.custom:/etc/nginx/conf.d/site.sogomiddleware.custom:ro,Z

  php-fpm-mailcow:
    volumes:
      - ./mailcow-roundcube/data/web/rc-auth.php:/web/rc-auth.php:ro,Z
      - ./mailcow-roundcube/data/web/SoGoMiddleware.php:/web/SoGoMiddleware.php:ro,Z
  